Metrics:
  Enabled: false
AllCops:
  Exclude:
    - 'test.rb'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'vendor/**/*'

Style/GlobalVars:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false