---
http_interactions:
- request:
    method: get
    uri: http://127.0.0.1:19090/api/v1/query?query=up
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Thu, 10 Aug 2017 09:36:04 GMT
      Content-Length:
      - '989'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"up","instance":"10.100.0.239:9100","job":"etcd"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.253:9100","job":"nodes"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.238:9100","job":"masters"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.36:9100","job":"nodes"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.249:9100","job":"nodes"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.77:9100","job":"masters"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.137:9100","job":"etcd"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.108:9100","job":"etcd"},"value":[1502357764.476,"1"]},{"metric":{"__name__":"up","instance":"10.100.0.58:9100","job":"masters"},"value":[1502357764.476,"1"]}]}}'
    http_version: 
  recorded_at: Thu, 10 Aug 2017 09:36:04 GMT
recorded_with: VCR 3.0.3
